'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime: 4.0.30319.18408
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My
    
    'NOTA: Esta clase se crea automáticamente por el tiempo de ejecución de Visual Basic.
    'No la modifique manualmente.
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("VB", "11.0")>  _
    Partial Friend Class MyApplication
        Inherits Global.System.Windows.Forms.ApplicationBase
        
        <Global.System.Diagnostics.DebuggerHidden()>  _
        Public Sub New()
            MyBase.New(Global.Microsoft.VisualBasic.ApplicationServices.AuthenticationMode.Windows)
            Me.IsSingleInstance = false
            Me.EnableVisualStyles = true
            Me.SaveMySettingsOnExit = true
            Me.ShutDownStyle = Global.Microsoft.VisualBasic.ApplicationServices.ShutdownMode.AfterMainFormCloses
        End Sub
        
        <Global.System.Diagnostics.DebuggerHidden()>  _
        Protected Overrides Sub OnCreateMainForm()
            Me.MainForm = CType(My.Forms.frmLogin,Global.frmLogin)
        End Sub
    End Class
End Namespace
